# Generated by Django 3.1.3 on 2020-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakaryawan',
            name='nik',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
