# Generated by Django 3.1.3 on 2020-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='dibuat_pada',
            field=models.DateTimeField(verbose_name='Dibuat pada'),
        ),
    ]
