# Generated by Django 3.1.3 on 2020-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201205_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
