# Generated by Django 3.1.3 on 2020-12-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_datakaryawan_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakaryawan',
            name='umur',
            field=models.IntegerField(null=True),
        ),
    ]
