# Generated by Django 3.1.3 on 2020-12-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tugas_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='kuantitas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tugas',
            name='selesai',
            field=models.IntegerField(null=True),
        ),
    ]
