# Generated by Django 3.1.3 on 2020-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201206_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='acc',
            field=models.IntegerField(null=True),
        ),
    ]
