# Generated by Django 3.1.3 on 2020-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tugas_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('Tuntas', 'Tuntas'), ('On Progress', 'On Progress'), ('Selesai', 'Selesai')], max_length=100),
        ),
    ]
