# Generated by Django 3.1.3 on 2020-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201206_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='selesai_pada',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
