# Generated by Django 3.1.3 on 2020-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_tugas_selesai_pada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('Tuntas', 'Tuntas'), ('Hold', 'Hold'), ('Stuck', 'Stuck'), ('On Progress', 'On Progress'), ('Selesai', 'Selesai'), ('Deadline', 'Deadline')], max_length=100),
        ),
    ]
