# Generated by Django 3.1.3 on 2020-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201208_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='selesai_pada',
            field=models.DateTimeField(null=True, verbose_name='Selesai pada'),
        ),
    ]
