# Generated by Django 3.1.3 on 2020-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201208_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKaryawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_id_fingerprint', models.IntegerField()),
                ('nik', models.CharField(max_length=4)),
                ('status_lamaran', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Office', 'Office'), ('Jatinangor', 'Jatinangor'), ('Cisitu', 'Cisitu'), ('Unjani', 'Unjani'), ('Metro', 'Metro'), ('Sukajadi', 'Sukajadi'), ('Telkom Sukabirus', 'Telkom Sukabirus'), ('Telkom Sukapura', 'Telkom Sukapura')], max_length=30)),
                ('level_manajemen', models.CharField(max_length=40)),
                ('nama_posisi', models.CharField(max_length=30)),
                ('kode_posisi', models.CharField(max_length=5)),
                ('status_jabatan', models.CharField(max_length=40, null=True)),
                ('jabatan_baru', models.CharField(max_length=40, null=True)),
                ('status_pegawai', models.CharField(max_length=50, null=True)),
                ('tanggal_masuk', models.DateTimeField(null=True, verbose_name='Tanggal Masuk')),
                ('no_ktp', models.CharField(max_length=30, null=True)),
                ('tempat_lahir', models.CharField(max_length=40, null=True)),
                ('tanggal_lahir', models.DateTimeField(null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
                ('agama', models.CharField(max_length=20, null=True)),
                ('pendidikan', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA/SMK', 'SMA/SMK'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10)),
                ('jurusan', models.CharField(max_length=40, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('no_hp', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('BELUM MENIKAH', 'BELUM MENIKAH'), ('MENIKAH', 'MENIKAH'), ('CERAI', 'CERAI')], max_length=20)),
                ('anak', models.IntegerField()),
                ('no_rekening', models.CharField(max_length=100, null=True)),
                ('bpjs_ketenagakerjaan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
