# Generated by Django 3.1.3 on 2020-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_datakaryawan_status_lamaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakaryawan',
            name='alamat_darurat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datakaryawan',
            name='hubungan_darurat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datakaryawan',
            name='nama_darurat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datakaryawan',
            name='no_hp_darurat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
