# Generated by Django 3.1.3 on 2020-12-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201216_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakaryawan',
            name='tanggal_lahir',
            field=models.DateField(null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='datakaryawan',
            name='tanggal_masuk',
            field=models.DateField(null=True, verbose_name='Tanggal Masuk'),
        ),
    ]
