# Generated by Django 3.1.3 on 2020-12-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_datakaryawan_alamat_darurat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakaryawan',
            name='pendidikan',
            field=models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10),
        ),
    ]
